# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: R

before_install:
  - sudo apt update
  - sudo apt install libudunits2-dev
  - sudo apt-get install libgdal1i
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install --yes libudunits2-dev libproj-dev libgeos-dev libgdal-dev
  - sudo apt-get install -y libsodium-dev
  - echo "options(repos = c(CRAN = 'https://packagemanager.rstudio.com/all/__linux__/xenial/latest'))" >> ~/.Rprofile.site
  - echo "options(HTTPUserAgent = paste0('R/', getRversion(), ' R (',
       paste(getRversion(), R.version['platform'], R.version['arch'], R.version['os']),
       ')'))" >> ~/.Rprofile.site

r_packages:
  - sf

r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'covr::codecov()'
