# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R

os: linux
dist: trusty

cache: packages

sudo: required

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libudunits2-dev
  brew_packages:
      - udunits
