#' Get Access Token
#'
#' Get an access token for accessing a service
#'
#' @param use_cache should the token be cached? Currently not working
#' @param auto_refresh should the token automatically be refreshed if it has expired?
#' @export get_token
#' @import httr
get_token <-
  function(use_cache = FALSE, auto_refresh = TRUE) {
    client_id <- "yKYDBnaubsMqB4qv"
    # Client secret embedded in source code as recomended by:
    # https://cran.r-project.org/web/packages/httr/vignettes/secrets.html
    client_secret <-"2337a5f0d4ba4ff3a8f3229b26303cc4"
    endpoint <-
      httr::oauth_endpoint(access = "https://www.arcgis.com/sharing/rest/oauth2/token/",
                     authorize  = "https://www.arcgis.com/sharing/rest/oauth2/authorize/")
    app <-
      httr::oauth_app(appname = "getarc",
                key = client_id,
                secret = client_secret,
                # When other people try to run get token they get an eror saying
                # incorrect redirect_uri. I wonder if this is because different users
                # have a different default uri. It is possible to reproduce the error by setting
                # the redirect uri below to one that doesn't match the app set up in arc
                # Doesn't work on RStudio Server
                redirect_uri = "http://localhost:1410/")

    # With the request send the datetime which is then automatically stored with the token
    # This is then checked against the expiry seconds and the token is refreshed if neccessary
    my_token <-
      httr::oauth2.0_token(endpoint = endpoint, app = app, cache = use_cache,
                           query_authorize_extra = list(grant_datetime = Sys.time()))

    # httr doesn't parse the credentials correctly into a list
    my_token$credentials <- jsonlite::fromJSON(my_token$credentials)

    # Check expiry and refresh if neccessary
    # The refresh token is an alteration to httr:::refresh_oauth2.0
    if(auto_refresh & token_expired(my_token)){
      my_token$credentials <-
        refresh_token(
          endpoint = endpoint,
          app = app,
          credentials = my_token$credentials,
          user_params = NULL
        )
      my_token$params$query_authorize_extra$grant_datetime <-
        Sys.time()
    }

    return(my_token)
  }

#' Token Expired
#'
#' Has the Oauth token expired
#'
#' @param my_token an access token generated by get_token
#' @return logical value detailing whether the token has or has not expired
#' @importFrom lubridate ymd_hms
#' @importFrom lubridate seconds
#' @importFrom jsonlite fromJSON
token_expired <-
  function(my_token){
    # Extract the grant time which is passed in when making the request
    grant_dttm <- my_token$params$query_authorize_extra$grant_datetime
    # and the expiry time which is in seconds
    expiry_seconds <- my_token$credentials$expires_in
    # calculate when the token expires and check whether this has occured yet
    expires_at <- lubridate::ymd_hms(grant_dttm) + lubridate::seconds(expiry_seconds)

    # There is something weird going on with timezones so I added the call to
    # ymd_hms, there is probably a better way of doing this to assert that the timezones are equal
    expired <- lubridate::ymd_hms(Sys.time()) > expires_at

    return(expired)
  }
