#' Get Layer Details
#'
#' Get the details of a layer
#'
#' @param endpoint the endpoint of the layer (can be generated by either \code{feature_server_endpoint} or \code{map_server_endpoint})
#' @param my_token an access token acquired by \code{get_token}
#' @return a list of parsed json
#' @import httr
#' @importFrom jsonlite fromJSON
#' @importFrom magrittr %>%
#'
get_layer_details <-
  function(endpoint, my_token = NULL) {
    # If a token has been passed to the function then parse it, otherwise NULL
    if (!is.null(my_token)) {
      token <- parse_access_token(my_token)
    } else{
      token <- my_token
    }
    # Build the parameters - json & token
    query_string <- query_string(my_token = my_token)

    query_url <- paste0(endpoint, query_string)

    response <- GET(query_url)

    # Convert the json to a list
    layer_details <- content(response) %>% fromJSON()

    return(layer_details)
  }
